# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Josh\Desktop\Python\YT Downloader\tutorial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(732, 614)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Josh\\Desktop\\Python\\YT Downloader\\../../../Downloads/youtube-logo-hd-8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.url_label = QtWidgets.QLabel(self.centralwidget)
        self.url_label.setGeometry(QtCore.QRect(20, 10, 701, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.url_label.setFont(font)
        self.url_label.setAlignment(QtCore.Qt.AlignCenter)
        self.url_label.setObjectName("url_label")
        self.url_text = QtWidgets.QTextEdit(self.centralwidget)
        self.url_text.setGeometry(QtCore.QRect(10, 50, 711, 41))
        self.url_text.setObjectName("url_text")
        self.audio_button = QtWidgets.QPushButton(self.centralwidget)
        self.audio_button.setGeometry(QtCore.QRect(10, 310, 361, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.audio_button.sizePolicy().hasHeightForWidth())
        self.audio_button.setSizePolicy(sizePolicy)
        self.audio_button.setMinimumSize(QtCore.QSize(10, 50))
        self.audio_button.setObjectName("audio_button")
        self.video_button = QtWidgets.QPushButton(self.centralwidget)
        self.video_button.setGeometry(QtCore.QRect(410, 310, 311, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_button.sizePolicy().hasHeightForWidth())
        self.video_button.setSizePolicy(sizePolicy)
        self.video_button.setMinimumSize(QtCore.QSize(10, 50))
        self.video_button.setObjectName("video_button")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 377, 711, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(10, 410, 711, 191))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.status_label.setFont(font)
        self.status_label.setText("")
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setWordWrap(True)
        self.status_label.setObjectName("status_label")
        self.url_list = QtWidgets.QListWidget(self.centralwidget)
        self.url_list.setGeometry(QtCore.QRect(10, 190, 711, 111))
        self.url_list.setObjectName("url_list")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(10, 100, 211, 41))
        self.add_button.setObjectName("add_button")
        self.remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_button.setGeometry(QtCore.QRect(260, 100, 211, 41))
        self.remove_button.setObjectName("remove_button")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(510, 100, 211, 41))
        self.clear_button.setObjectName("clear_button")
        self.url_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.url_label_2.setGeometry(QtCore.QRect(10, 150, 711, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.url_label_2.setFont(font)
        self.url_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.url_label_2.setObjectName("url_label_2")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Arctic\'s YouTube downloader"))
        self.url_label.setText(_translate("mainWindow", "Enter URL Below"))
        self.audio_button.setToolTip(_translate("mainWindow", "Dowloads your Youtube link in audio format"))
        self.audio_button.setText(_translate("mainWindow", "Audio"))
        self.video_button.setToolTip(_translate("mainWindow", "Dowloads your Youtube link in video format"))
        self.video_button.setText(_translate("mainWindow", "Video"))
        self.add_button.setText(_translate("mainWindow", "Add URL to list"))
        self.remove_button.setText(_translate("mainWindow", "Remove URL from list"))
        self.clear_button.setText(_translate("mainWindow", "Clear URL list"))
        self.url_label_2.setText(_translate("mainWindow", "URL List:"))
