# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Josh\Desktop\Python\YT Downloader\tutorial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(615, 319)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Josh\\Desktop\\Python\\YT Downloader\\../../../Downloads/youtube-logo-hd-8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.url_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.url_label.setFont(font)
        self.url_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.url_label.setObjectName("url_label")
        self.gridLayout.addWidget(self.url_label, 0, 0, 1, 1)
        self.url_text = QtWidgets.QTextEdit(self.centralwidget)
        self.url_text.setObjectName("url_text")
        self.gridLayout.addWidget(self.url_text, 0, 1, 1, 1)
        self.audio_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.audio_button.sizePolicy().hasHeightForWidth())
        self.audio_button.setSizePolicy(sizePolicy)
        self.audio_button.setMinimumSize(QtCore.QSize(10, 50))
        self.audio_button.setObjectName("audio_button")
        self.gridLayout.addWidget(self.audio_button, 1, 0, 1, 2)
        self.video_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_button.sizePolicy().hasHeightForWidth())
        self.video_button.setSizePolicy(sizePolicy)
        self.video_button.setMinimumSize(QtCore.QSize(10, 50))
        self.video_button.setObjectName("video_button")
        self.gridLayout.addWidget(self.video_button, 2, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 2)
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.status_label.setFont(font)
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 4, 0, 1, 2)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Arctic\'s YouTube downloader"))
        self.url_label.setText(_translate("mainWindow", "URL:"))
        self.audio_button.setToolTip(_translate("mainWindow", "Dowloads your Youtube link in audio format"))
        self.audio_button.setText(_translate("mainWindow", "Audio"))
        self.video_button.setToolTip(_translate("mainWindow", "Dowloads your Youtube link in video format"))
        self.video_button.setText(_translate("mainWindow", "Video"))
